return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    tag = "v0.10.0",
    lazy = false,
    opts = {
        ensure_installed = {
            "go",
            "lua",
            "regex",
            "bash",
            "markdown",
            "markdown_inline",
            "sql",
            "php",
            "phpdoc",
            "vue",
            "angular",
            "html",
            "css",
            "scss",
            "javascript",
            "typescript",
            "tsx",
            "json",
            "java",
            "python",
        },
        auto_install = false,
        highlight = {
            enable = true,
            additional_vim_regex_highlighting = false,
        },
        indent = {
            enable = false,
        },
    },
}
